/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
/**
 * This sample demonstrates how to Power off virtual machine, options: shutdown, poweroff, and suspend
 *
 * @summary Power off virtual machine, options: shutdown, poweroff, and suspend
 * x-ms-original-file: specification/vmwarecloudsimple/resource-manager/Microsoft.VMwareCloudSimple/stable/2019-04-01/examples/StopInBodyVirtualMachine.json
 */
import {
  VirtualMachineStopMode,
  VMwareCloudSimple
} from "@azure/arm-vmwarecloudsimple";
import { DefaultAzureCredential } from "@azure/identity";

async function stopInBodyVirtualMachine() {
  const subscriptionId = "{subscription-id}";
  const resourceGroupName = "myResourceGroup";
  const referer = "https://management.azure.com/";
  const virtualMachineName = "myVirtualMachine";
  const m: VirtualMachineStopMode = {};
  const options = { m: m as VirtualMachineStopMode };
  const credential = new DefaultAzureCredential();
  const client = new VMwareCloudSimple(credential, subscriptionId);
  const result = await client.virtualMachines.beginStopAndWait(
    resourceGroupName,
    referer,
    virtualMachineName,
    options
  );
  console.log(result);
}

stopInBodyVirtualMachine().catch(console.error);
