import { Dirent, readdirSync, readFileSync } from "fs";
import path from "path";
import { getDirname } from "../../src/utils/dirname.js";

const { __dirname } = getDirname(import.meta.url);

export const modularUnitRoot = path.resolve(__dirname, "..", "modularUnit");
export const scenarioSpecsRoot = path.join(modularUnitRoot, "scenario-specs");

export function getExpectedScenarioSpecFiles(): Map<string, string> {
  const expectedFiles = new Map<string, string>();
  const directories = listScenarioDirectories(modularUnitRoot).sort();

  for (const scenarioDirectory of directories) {
    const relativeFilePath = `${scenarioDirectory}.spec.ts`;
    const wrapperPath = path.join(scenarioSpecsRoot, relativeFilePath);
    const wrapperDirectory = path.dirname(wrapperPath);
    const helperImport = getHelperImportPath(wrapperDirectory);
    const normalizedScenarioDirectory = scenarioDirectory
      .split(path.sep)
      .join("/");
    const content = `// Generated by test/commands/generate-modular-scenario-specs.ts
import { registerScenarioDirectoryTests } from "${helperImport}";

registerScenarioDirectoryTests("${normalizedScenarioDirectory}");
`;

    expectedFiles.set(relativeFilePath.split(path.sep).join("/"), content);
  }

  return expectedFiles;
}

export function getActualScenarioSpecFiles(): Map<string, string> {
  return collectFiles(scenarioSpecsRoot);
}

function collectFiles(root: string): Map<string, string> {
  const files = new Map<string, string>();
  if (!exists(root)) {
    return files;
  }

  for (const entry of readdirSync(root, { withFileTypes: true }).sort(
    compareDirents
  )) {
    const fullPath = path.join(root, entry.name);
    if (entry.isDirectory()) {
      for (const [relativePath, content] of collectFiles(fullPath)) {
        files.set(
          path.join(entry.name, relativePath).split(path.sep).join("/"),
          content
        );
      }
      continue;
    }

    if (entry.isFile() && entry.name.endsWith(".spec.ts")) {
      files.set(entry.name, readFileSync(fullPath, "utf8"));
    }
  }

  return files;
}

function exists(directory: string): boolean {
  try {
    readdirSync(directory);
    return true;
  } catch {
    return false;
  }
}

function listScenarioDirectories(modularUnitDirectory: string): string[] {
  const scenariosRoot = path.join(modularUnitDirectory, "scenarios");
  return findScenarioDirectories(scenariosRoot, scenariosRoot);
}

function findScenarioDirectories(
  scenariosRoot: string,
  currentDirectory: string
): string[] {
  const entries = readdirSync(currentDirectory, {
    withFileTypes: true
  }).sort(compareDirents);
  const directories: string[] = [];

  if (entries.some((entry) => entry.isFile() && entry.name.endsWith(".md"))) {
    directories.push(path.relative(scenariosRoot, currentDirectory));
  }

  for (const entry of entries) {
    if (!entry.isDirectory()) {
      continue;
    }

    directories.push(
      ...findScenarioDirectories(
        scenariosRoot,
        path.join(currentDirectory, entry.name)
      )
    );
  }

  return directories;
}

function compareDirents(left: Dirent, right: Dirent): number {
  return left.name.localeCompare(right.name);
}

function getHelperImportPath(wrapperDirectory: string): string {
  const helperPath = path.join(modularUnitRoot, "scenarioHarness.ts");
  const relativePath = path.relative(wrapperDirectory, helperPath);
  return relativePath.replace(/\.ts$/, ".js").split(path.sep).join("/");
}
