steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Use Node 20"
  - script: |
      npm install -g pnpm
    displayName: "Install Pnpm"
  - script: |
      pnpm install
      pnpm build
    displayName: "Build"
