trigger:
  - v6

parameters:
  - name: LinuxPool
    type: string
    default: azsdk-pool-mms-ubuntu-1804-general
  - name: IncludeRelease
    type: boolean
    default: true
  - name: OSVmImage
    type: string
    default: ubuntu-18.04

pool:
  vmImage: ubuntu-18.04

stages:
  - stage: BuildStage
    jobs:
      - job: Build
        steps:
          - template: build.yml
          - script: |
              export MAIN_VERSION=$(node -p -e "require('./package.json').version")
              echo "##vso[task.setvariable variable=MAIN_VERSION;isOutput=true;]MAIN_VERSION"
            name: SetMainVersion
          - script: |
              export DEV_VERSION=$(node -p -e "require('./package.json').version.replace('beta', 'alpha')").$(Build.BuildNumber)
              echo "##vso[task.setvariable variable=DEV_VERSION;isOutput=true;]$DEV_VERSION"
              npm version --no-git-tag-version $DEV_VERSION
            condition: or(eq(variables['SetDevVersion'], 'true'), and(eq(variables['SetDevVersion'], ''), eq(variables['Build.Reason'],'Schedule'), eq(variables['System.TeamProject'], 'internal')))
            name: SetDevVersion
          - script: |
              export TAR_NAME=$(npm pack -q)
              echo "##vso[task.setvariable variable=TAR_NAME;isOutput=true;]$TAR_NAME"
            name: PackArtifacts
          - task: CopyFiles@2
            inputs:
              contents: "*.tgz"
              targetFolder: $(Build.ArtifactStagingDirectory)
              flattenFolders: true
            displayName: "Copy packages"

          - task: PublishPipelineArtifact@1
            condition: succeededOrFailed()
            displayName: "Publish artifacts"
            inputs:
              artifactName: packages
              path: $(Build.ArtifactStagingDirectory)

  # The Prerelease and Release stages are conditioned on whether we are building a pull request and the branch.
  - ? ${{if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'internal'), eq(parameters.IncludeRelease,true))}}
    : - template: release.yml
        parameters:
          DependsOn: BuildStage
