trigger:
  - v6

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: Build
    steps:
      - template: build.yml
      - script: npm run test
        displayName: "Run Tests"

      - script: npm run check:tree
        displayName: "Check git Tree"

      - script: |
          npm run coverage-push -- $(Build.Repository.Name) $(Build.SourceBranch) $(github-token) $(storage-coverage-user) $(storage-coverage-pass)
        workingDirectory: node_modules/@microsoft.azure/autorest.testserver
        displayName: "Upload Coverage Report"

  - template: smoke-test.yml
    parameters:
      name: SmokeTest_1
      tag: ci_1

  - template: smoke-test.yml
    parameters:
      name: SmokeTest_2
      tag: ci_2

  - template: smoke-test.yml
    parameters:
      name: SmokeTest_3
      tag: ci_3
