trigger:
  - v6

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Build'

- script: |
    npm run test
    npm run check:tree
  displayName: 'Run Tests'

- script: |
    npm run clone:specs
  displayName: 'Clone Specs Repository'

- script: |
    npm run smoke-test
    npm run check:tree
  displayName: 'Run Smoke Tests'

- script: |
    npm run coverage-push -- $(Build.Repository.Name) $(Build.SourceBranch) $(github-token) $(storage-coverage-user) $(storage-coverage-pass)
  workingDirectory: node_modules/@microsoft.azure/autorest.testserver
  displayName: 'Upload Coverage Report'
