trigger:
  - v6

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build
    steps:
    - template: build.yml
    - script: npm run test
      displayName: 'Run Tests'

    - script: npm run check:tree
      displayName: 'Check git Tree'

    - script: |
        npm run coverage-push -- $(Build.Repository.Name) $(Build.SourceBranch) $(github-token) $(storage-coverage-user) $(storage-coverage-pass)
      workingDirectory: node_modules/@microsoft.azure/autorest.testserver
      displayName: 'Upload Coverage Report'

  - job: SmokeTest
    steps:
    - template: build.yml
    - script: npm run clone:specs
      displayName: 'Clone Specs Repository'

    - script: npm run smoke-test
      displayName: 'Run Smoke Tests'

    - script: npm run check:tree
      displayName: 'Check git Tree'