trigger: none
schedules:
  - cron: "0 12 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - main
pr: none

stages:
  - stage: NightlyCI
    jobs:
      - job: CadlRanchTest
        steps:
          - template: nightly-prepare.yml
          - script: npm run e2e-test-ci
            workingDirectory: $(Build.SourcesDirectory)/packages/typespec-ts
            displayName: "Run all Cadl-ranch test cases"
      - job: IntegrationTest
        steps:
          - template: nightly-prepare.yml
          - script: npm run integration-test
            workingDirectory: $(Build.SourcesDirectory)/packages/typespec-ts
            displayName: "Run all integration test cases"
      - job: UnitTest
        steps:
          - template: nightly-prepare.yml
          - script: npm run unit-test
            workingDirectory: $(Build.SourcesDirectory)/packages/typespec-ts
            displayName: "Run all Unit test cases"
      - job: SmokeTest
        steps:
          - template: nightly-prepare.yml
          - script: node $(Build.SourcesDirectory)/common/scripts/install-run-rushx.js smoke-test
            workingDirectory: $(Build.SourcesDirectory)/packages/typespec-test
            displayName: "Generate Code From TypeSpec"
