trigger: none
schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - main
pr: none

steps:
  - script: npm install -g @typespec/compiler@next
    displayName: Install @typespec/compiler@next
  - script: npm run override-dev-version
    workingDirectory: $(Build.SourcesDirectory)/packages/typespec-ts
    displayName: "Override tsp version to latest dev"
  - template: build.yml
  - script: npm list
    workingDirectory: $(Build.SourcesDirectory)/packages/typespec-ts
    displayName: "List current install version"
  - script: npm run test
    workingDirectory: $(Build.SourcesDirectory)/packages/typespec-ts
    displayName: "Generate RLC Test Clients from Cadl-ranch"
