parameters:
  - name: DependsOn
    type: string
    default: Build

  - name: LinuxPool
    type: string
    default: azsdk-pool-mms-ubuntu-2004-general

  - name: OSVmImage
    type: string
    default: ubuntu-20.04

stages:
  - ${{if and(eq(variables['Build.Reason'], 'Manual'), eq(variables['System.TeamProject'], 'internal'))}}:
      - stage: AutorestTypescriptRelease
        displayName: "Release: @autorest/typescript"
        dependsOn: ${{parameters.DependsOn}}
        jobs:
          - deployment: TagRepository
            displayName: "Create release tag"
            condition: and(ne(variables['Skip.TagRepository'], 'true'), ne(variables['SetDevVersion'], 'true'))
            environment: github

            pool:
              name: ${{ parameters.LinuxPool }}
              vmImage: ${{ parameters.OSVmImage }}

            variables:
              MAIN_VERSION: $[ stageDependencies.BuildStage.Build.outputs['PackAutorestTypescriptArtifacts.MAIN_VERSION'] ]
              TAR_NAME: $[ stageDependencies.BuildStage.Build.outputs['PackAutorestTypescriptArtifacts.TAR_NAME'] ]

            strategy:
              runOnce:
                deploy:
                  steps:
                    - task: NodeTool@0
                      inputs:
                        versionSpec: "16.x"
                      displayName: "Install Node.js"
                    - script: |
                        tar zxvf $(Pipeline.Workspace)/packages/$(TAR_NAME)
                    - script: |
                        cd package
                        npx publish-release --token $(azuresdk-github-pat) --repo autorest.typescript --owner azure --name v$(MAIN_VERSION) --tag v$(MAIN_VERSION) --notes='release  build' --prerelease --editRelease false --assets $(Pipeline.Workspace)/packages/$(TAR_NAME) --target_commitish $(Build.SourceBranchName)
                      displayName: "Publish @autorest/typescript to GitHub"
          - deployment: PublishToNpm
            variables:
              TAR_NAME: $[ stageDependencies.BuildStage.Build.outputs['PackAutorestTypescriptArtifacts.TAR_NAME'] ]
            environment: npm
            displayName: Publish @autorest/typescript to NPM
            condition: ne(variables['SetDevVersion'], 'true')
            pool:
              name: ${{ parameters.LinuxPool }}
              vmImage: ${{ parameters.OSVmImage }}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - task: NodeTool@0
                      inputs:
                        versionSpec: "16.x"
                      displayName: "Install Node.js"
                    - script: |
                        cd $(Pipeline.Workspace)/packages
                        npm config set //registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)
                        npm publish $(TAR_NAME) --access public --tag latest
                        npm config delete //registry.npmjs.org/:_authToken
                      displayName: "Publish to NPM"
      - stage: TypeSpecTSRelease
        displayName: "Release: @azure-tools/typespec-ts"
        dependsOn: ${{parameters.DependsOn}}
        jobs:
          - deployment: TagRepository
            displayName: "Create release tag"
            condition: and(ne(variables['Skip.TagRepository'], 'true'), ne(variables['SetDevVersion'], 'true'))
            environment: github

            pool:
              name: ${{ parameters.LinuxPool }}
              vmImage: ${{ parameters.OSVmImage }}

            variables:
              MAIN_VERSION: $[ stageDependencies.BuildStage.Build.outputs['PackTypeSpecTSArtifacts.MAIN_VERSION'] ]
              TAR_NAME: $[ stageDependencies.BuildStage.Build.outputs['PackTypeSpecTSArtifacts.TAR_NAME'] ]

            strategy:
              runOnce:
                deploy:
                  steps:
                    - task: NodeTool@0
                      inputs:
                        versionSpec: "16.x"
                      displayName: "Install Node.js"
                    - script: |
                        tar zxvf $(Pipeline.Workspace)/packages/$(TAR_NAME)
                    - script: |
                        cd package
                        npx publish-release --token $(azuresdk-github-pat) --repo autorest.typescript --owner azure --name v$(MAIN_VERSION) --tag v$(MAIN_VERSION) --notes='release  build' --prerelease --editRelease false --assets $(Pipeline.Workspace)/packages/$(TAR_NAME) --target_commitish $(Build.SourceBranchName)
                      displayName: "Publish @azure-tools/typespec-ts to GitHub"
          - deployment: PublishToNpm
            variables:
              TAR_NAME: $[ stageDependencies.BuildStage.Build.outputs['PackTypeSpecTSArtifacts.TAR_NAME'] ]
            environment: npm
            displayName: Publish @azure-tools/typespec-ts to NPM
            condition: ne(variables['SetDevVersion'], 'true')
            pool:
              name: ${{ parameters.LinuxPool }}
              vmImage: ${{ parameters.OSVmImage }}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - task: NodeTool@0
                      inputs:
                        versionSpec: "16.x"
                      displayName: "Install Node.js"
                    - script: |
                        cd $(Pipeline.Workspace)/packages
                        npm config set //registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)
                        npm publish $(TAR_NAME) --access public --tag latest
                        npm config delete //registry.npmjs.org/:_authToken
                      displayName: "Publish to NPM"

      - stage: RLCCommonRelease
        displayName: "Release: @azure-tools/rlc-common"
        dependsOn: ${{parameters.DependsOn}}
        jobs:
          - deployment: TagRepository
            displayName: "Create release tag"
            condition: and(ne(variables['Skip.TagRepository'], 'true'), ne(variables['SetDevVersion'], 'true'))
            environment: github

            pool:
              name: ${{ parameters.LinuxPool }}
              vmImage: ${{ parameters.OSVmImage }}

            variables:
              MAIN_VERSION: $[ stageDependencies.BuildStage.Build.outputs['PackRLCCommonArtifacts.MAIN_VERSION'] ]
              TAR_NAME: $[ stageDependencies.BuildStage.Build.outputs['PackRLCCommonArtifacts.TAR_NAME'] ]

            strategy:
              runOnce:
                deploy:
                  steps:
                    - task: NodeTool@0
                      inputs:
                        versionSpec: "16.x"
                      displayName: "Install Node.js"
                    - script: |
                        tar zxvf $(Pipeline.Workspace)/packages/$(TAR_NAME)
                    - script: |
                        cd package
                        npx publish-release --token $(azuresdk-github-pat) --repo autorest.typescript --owner azure --name v$(MAIN_VERSION) --tag v$(MAIN_VERSION) --notes='release  build' --prerelease --editRelease false --assets $(Pipeline.Workspace)/packages/$(TAR_NAME) --target_commitish $(Build.SourceBranchName)
                      displayName: "Publish @azure-tools/rlc-common to GitHub"
          - deployment: PublishToNpm
            variables:
              TAR_NAME: $[ stageDependencies.BuildStage.Build.outputs['PackRLCCommonArtifacts.TAR_NAME'] ]
            environment: npm
            displayName: Publish @azure-tools/rlc-commo to NPM
            condition: ne(variables['SetDevVersion'], 'true')
            pool:
              name: ${{ parameters.LinuxPool }}
              vmImage: ${{ parameters.OSVmImage }}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - task: NodeTool@0
                      inputs:
                        versionSpec: "16.x"
                      displayName: "Install Node.js"
                    - script: |
                        cd $(Pipeline.Workspace)/packages
                        npm config set //registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)
                        npm publish $(TAR_NAME) --access public --tag latest
                        npm config delete //registry.npmjs.org/:_authToken
                      displayName: "Publish to NPM"

  - stage: Integration
    dependsOn: ${{parameters.DependsOn}}
    jobs:
      - deployment: PublishAutorestTypescriptToGithub
        condition: or(eq(variables['SetDevVersion'], 'true'), and(eq(variables['SetDevVersion'], ''), eq(variables['Build.Reason'],'Schedule'), eq(variables['System.TeamProject'], 'internal')))
        variables:
          TAR_NAME: $[ stageDependencies.BuildStage.Build.outputs['PackAutorestTypescriptArtifacts.TAR_NAME'] ]
          DEV_VERSION: $[ stageDependencies.BuildStage.Build.outputs['SetAutorestTypescriptDevVersion.DEV_VERSION'] ]
        environment: githubtsjssdk
        displayName: Publish @autorest/typescript dev version to GitHub
        pool:
          name: ${{ parameters.LinuxPool }}
          vmImage: ${{ parameters.OSVmImage }}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: NodeTool@0
                  inputs:
                    versionSpec: "16.x"
                  displayName: "Install Node.js"
                - script: |
                    tar zxvf $(Pipeline.Workspace)/packages/$(TAR_NAME)
                - script: |
                    cd package
                    tree .
                    npx publish-release --token $(azuresdk-github-pat) --repo autorest.typescript --owner azure --name v$(DEV_VERSION) --tag v$(DEV_VERSION) --notes='prerelease build' --prerelease --editRelease false --assets $(Pipeline.Workspace)/packages/$(TAR_NAME) --target_commitish $(Build.SourceBranchName)
                  displayName: "Publish @autorest/typescript to GitHub"
      - deployment: PublishTypeSpecTSToGithub
        condition: or(eq(variables['SetDevVersion'], 'true'), and(eq(variables['SetDevVersion'], ''), eq(variables['Build.Reason'],'Schedule'), eq(variables['System.TeamProject'], 'internal')))
        variables:
          TAR_NAME: $[ stageDependencies.BuildStage.Build.outputs['PackTypeSpecTSArtifacts.TAR_NAME'] ]
          DEV_VERSION: $[ stageDependencies.BuildStage.Build.outputs['SetTypeSpecTSDevVersion.DEV_VERSION'] ]
        environment: githubtsjssdk
        displayName: Publish @azure-tools/typespec-ts dev version to GitHub
        pool:
          name: ${{ parameters.LinuxPool }}
          vmImage: ${{ parameters.OSVmImage }}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: NodeTool@0
                  inputs:
                    versionSpec: "16.x"
                  displayName: "Install Node.js"
                - script: |
                    tar zxvf $(Pipeline.Workspace)/packages/$(TAR_NAME)
                - script: |
                    cd package
                    tree .
                    npx publish-release --token $(azuresdk-github-pat) --repo autorest.typescript --owner azure --name v$(DEV_VERSION) --tag v$(DEV_VERSION) --notes='prerelease build' --prerelease --editRelease false --assets $(Pipeline.Workspace)/packages/$(TAR_NAME) --target_commitish $(Build.SourceBranchName)
                  displayName: "Publish @azure-tools/typespec-ts to GitHub"
      - deployment: PublishRLCCommonToGithub
        condition: or(eq(variables['SetDevVersion'], 'true'), and(eq(variables['SetDevVersion'], ''), eq(variables['Build.Reason'],'Schedule'), eq(variables['System.TeamProject'], 'internal')))
        variables:
          TAR_NAME: $[ stageDependencies.BuildStage.Build.outputs['PackRLCCommonArtifacts.TAR_NAME'] ]
          DEV_VERSION: $[ stageDependencies.BuildStage.Build.outputs['SetRLCCommonDevVersion.DEV_VERSION'] ]
        environment: githubtsjssdk
        displayName: Publish @azure-tools/rlc-common dev version to GitHub
        pool:
          name: ${{ parameters.LinuxPool }}
          vmImage: ${{ parameters.OSVmImage }}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: NodeTool@0
                  inputs:
                    versionSpec: "16.x"
                  displayName: "Install Node.js"
                - script: |
                    tar zxvf $(Pipeline.Workspace)/packages/$(TAR_NAME)
                - script: |
                    cd package
                    tree .
                    npx publish-release --token $(azuresdk-github-pat) --repo autorest.typescript --owner azure --name v$(DEV_VERSION) --tag v$(DEV_VERSION) --notes='prerelease build' --prerelease --editRelease false --assets $(Pipeline.Workspace)/packages/$(TAR_NAME) --target_commitish $(Build.SourceBranchName)
                  displayName: "Publish @azure-tools/rlc-common to GitHub"
      - deployment: PublishAutorestTypescriptToNpm
        condition: or(eq(variables['SetDevVersion'], 'true'), and(eq(variables['SetDevVersion'], ''), eq(variables['Build.Reason'],'Schedule'), eq(variables['System.TeamProject'], 'internal')))
        variables:
          TAR_NAME: $[ stageDependencies.BuildStage.Build.outputs['PackAutorestTypescriptArtifacts.TAR_NAME'] ]
        environment: npmtsjssdk
        displayName: Publish @autorest/typescript dev version to NPM
        pool:
          name: ${{ parameters.LinuxPool }}
          vmImage: ${{ parameters.OSVmImage }}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: NodeTool@0
                  inputs:
                    versionSpec: "16.x"
                  displayName: "Install Node.js"
                - script: |
                    cd $(Pipeline.Workspace)/packages
                    npm config set //registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)
                    npm publish $(TAR_NAME) --access public --tag dev
                    npm config delete //registry.npmjs.org/:_authToken
                  displayName: "Publish @autorest/typescript to NPM"
      - deployment: PublishCadlAutorestToNpm
        condition: or(eq(variables['SetDevVersion'], 'true'), and(eq(variables['SetDevVersion'], ''), eq(variables['Build.Reason'],'Schedule'), eq(variables['System.TeamProject'], 'internal')))
        variables:
          TAR_NAME: $[ stageDependencies.BuildStage.Build.outputs['PackTypeSpecTSArtifacts.TAR_NAME'] ]
        environment: npmtsjssdk
        displayName: Publish @azure-tools/cadl-autorest dev version to NPM
        pool:
          name: ${{ parameters.LinuxPool }}
          vmImage: ${{ parameters.OSVmImage }}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: NodeTool@0
                  inputs:
                    versionSpec: "16.x"
                  displayName: "Install Node.js"
                - script: |
                    cd $(Pipeline.Workspace)/packages
                    npm config set //registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)
                    npm publish $(TAR_NAME) --access public --tag dev
                    npm config delete //registry.npmjs.org/:_authToken
                  displayName: "Publish @azure-tools/typespec-ts to NPM"
      - deployment: PublishRLCCommonToNpm
        condition: or(eq(variables['SetDevVersion'], 'true'), and(eq(variables['SetDevVersion'], ''), eq(variables['Build.Reason'],'Schedule'), eq(variables['System.TeamProject'], 'internal')))
        variables:
          TAR_NAME: $[ stageDependencies.BuildStage.Build.outputs['PackRLCCommonArtifacts.TAR_NAME'] ]
        environment: npmtsjssdk
        displayName: Publish @azure-tools/rlc-common dev version to NPM
        pool:
          name: ${{ parameters.LinuxPool }}
          vmImage: ${{ parameters.OSVmImage }}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: NodeTool@0
                  inputs:
                    versionSpec: "16.x"
                  displayName: "Install Node.js"
                - script: |
                    cd $(Pipeline.Workspace)/packages
                    npm config set //registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)
                    npm publish $(TAR_NAME) --access public --tag dev
                    npm config delete //registry.npmjs.org/:_authToken
                  displayName: "Publish @azure-tools/rlc-common to NPM"
