parameters:
  - name: DependsOn
    type: string
    default: Build

  - name: PublishAlpha
    type: boolean
    default: false

  - name: LinuxPool
    type: string
    default: azsdk-pool-mms-ubuntu-1804-general

  - name: OSVmImage
    type: string
    default: ubuntu-18.04

stages:
  - ${{if eq(parameters.PublishAlpha, 'true')}}:
      - stage: Integration
        dependsOn: ${{parameters.DependsOn}}
        jobs:
          - deployment: PublishToGithub
            environment: github
            displayName: Publish dev version to GitHub
            pool:
              name: ${{ parameters.LinuxPool }}
              vmImage: ${{ parameters.OSVmImage }}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: self
                    - task: NodeTool@0
                      inputs:
                        versionSpec: "14.x"
                      displayName: "Install Node.js"
                    - script: |
                        npm install
                        npm run build
                      displayName: "npm install and build"
                    - script: |
                        export DEV_VERSION=$(node -p -e "require('./package.json').version")-alpha.$BUILD_BUILDNUMBER
                        npm version --no-git-tag-version $DEV_VERSION
                        npm pack
                      displayName: "Publish to GitHub"
          - deployment: PublishToNpm
            environment: npm
            displayName: Publish dev version to NPM
            pool:
              name: $[coalesce(variables['Pool'], '')]
              vmImage: $[coalesce(variables['OSVmImage'], '')]
            strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: self
                    - task: NodeTool@0
                      inputs:
                        versionSpec: "14.x"
                      displayName: "Install Node.js"
                    - script: |
                        npm install
                        npm run build
                      displayName: "npm install and build"
                    - script: |
                        export DEV_VERSION=$(node -p -e "require('./package.json').version")-alpha.$BUILD_BUILDNUMBER
                        npm version --no-git-tag-version $DEV_VERSION
                      displayName: "Set Dev Version"
                    - script: |
                        export TAR_NAME=$(npm pack -q)
                        echo $TAR_NAME
                      displayName: "Npm Pack"
                    - script: |
                        echo "//registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)" > ./.npmrc
                        npm publish --dry-run $TAR_NAME --access-level="public" --registry="https://registry.npmjs.org/" --always-auth=true --tag="dev"
                      displayName: "Publish to NPM"
