parameters:
  name: ""
  tag: ""

jobs:
  - job: ${{ parameters.name }}
    variables:
      - template: globals.yml
    strategy:
      matrix:
        Linux_Node18:
          Pool: azsdk-pool-mms-ubuntu-2004-general
          OSVmImage: "ubuntu-20.04"
          NodeTestVersion: "18.x"
    pool:
      name: $[coalesce(variables['Pool'], '')]
      vmImage: $[coalesce(variables['OSVmImage'], '')]
    steps:
      - template: build.yml
      - script: npm run clone:specs
        workingDirectory: $(Build.SourcesDirectory)/packages/autorest.typescript
        displayName: "Clone Specs Repository"

      - script: npm run smoke-test -- --tag=${{ parameters.tag }}
        workingDirectory: $(Build.SourcesDirectory)/packages/autorest.typescript
        displayName: "Run Smoke Tests"

      - script: npm run check:tree
        workingDirectory: $(Build.SourcesDirectory)/packages/autorest.typescript
        displayName: "Check git Tree"
