parameters:
  name: ""
  tag: ""

jobs:
  - job: ${{ parameters.name }}
    variables:
      - template: globals.yml
    strategy:
      matrix:
        macOS_Node18:
          Pool:
          OSVmImage: "macOS-latest"
          NodeTestVersion: "18.x"
        Linux_Node18:
          Pool: ${{ parameters.LinuxPool }}
          OSVmImage: "ubuntu-20.04"
          NodeTestVersion: "18.x"
        Windows_Latest:
          Pool:
          OSVmImage: "Windows-latest"
          NodeTestVersion: "18.x"
    steps:
      - template: build.yml
      - script: npm run clone:specs
        workingDirectory: $(Build.SourcesDirectory)/packages/autorest.typescript
        displayName: "Clone Specs Repository"

      - script: npm run smoke-test -- --tag=${{ parameters.tag }}
        workingDirectory: $(Build.SourcesDirectory)/packages/autorest.typescript
        displayName: "Run Smoke Tests"

      - script: npm run check:tree
        workingDirectory: $(Build.SourcesDirectory)/packages/autorest.typescript
        displayName: "Check git Tree"
